name: Adventskalendar
main: de.whsminecraft.Adventskalendar.Main
author: Ruben Ollesch
api-version: 1.17
version: 1.0
website: https://whsminecraft.de
commands:
  advent:
    description: Öffne ein Türchen des Adventskalendars
    usage: /advent
